[package]
name = "contender_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "contender"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }
serde = { workspace = true }
contender_core = { workspace = true }
contender_sqlite = { workspace = true }
contender_testfile = { workspace = true }

clap = { workspace = true, features = ["derive"] }
alloy = { workspace = true, features = ["full", "node-bindings", "rpc-types-debug", "rpc-types-trace"] }
csv = { workspace = true }
handlebars = { workspace = true }
termcolor = "1.4.1"
rand.workspace = true
serde_json = { workspace = true }
plotters = { workspace = true }
webbrowser = { workspace = true }
chrono = "0.4.39"
regex = "1.11.1"
log = "0.4.25"

[dev-dependencies]
tempfile = "3.15.0"
