[package]
name = "contender_core"
version = "0.1.0"
edition = "2021"
authors = ["Brock Smedley"]

[lib]
name = "contender_core"
path = "src/lib.rs"

[dependencies]
alloy = { workspace = true, features = ["full", "node-bindings", "rpc-types-mev"] }
# eyre = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
futures = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["signal"]}
serde_json = { workspace = true }
contender_bundle_provider = { workspace = true }
tokio-tungstenite = "0.23.1"
url = "2.5"
